# src/module-3/nav2_configs/nav2_params.yaml
# Placeholder for Nav2 configuration parameters

# Common parameters for all Nav2 nodes
ros__parameters:
  use_sim_time: True

  # Controller Server
  controller_server:
    ros__parameters:
      controller_plugin_ids: ["FollowPath"]
      controller_plugin_types: ["nav2_controller::SimpleProgressChecker"] # Placeholder

  # Planner Server
  planner_server:
    ros__parameters:
      use_sim_time: True
      planner_plugin_ids: ["GridBased"] # Placeholder
      planner_plugin_types: ["nav2_planner::GridBased"] # Placeholder

  # Behavior Tree Navigator
  bt_navigator:
    ros__parameters:
      use_sim_time: True
      global_frame: map
      robot_base_frame: base_link
      # Plugins and other specific parameters would go here

  # Costmap (local and global)
  # These would typically be separate files and included. For placeholder, a minimal common set.
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05
      static_map: false
      rolling_window: true
      width: 3.0
      height: 3.0
      plugins: ["obstacle_layer", "inflation_layer"] # Placeholder
      # Obstacle layer, inflation layer configurations

  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 1.0
      publish_frequency: 1.0
      resolution: 0.05
      static_map: true # Assumes a static map from VSLAM
      # Plugins and other specific parameters

# Full configurations would be much more extensive and tailored to the robot and environment.
# This serves as a starting point.
